title = "ESA QERC"
baseURL = "https://esa-qerc.github.io/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  description = "Connecting Australia's Quantitative Ecologists"
  twitter = "https://twitter.com/esa_qerc"
  github = "https://github.com/esa-qerc"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "/images/qerc_banner_bg.png"
  recent_posts_number = 3
